sudo: required
services:
- docker
language: c
cache:
  directories:
  - ".go/pkg/mod/cache"
  - ".go/cache"
jobs:
  include:
  - stage: test
    script:
    - make docs
  - stage: test
    install:
    - make go-mod-download
    before_script:
    - make start-kind
    script:
    - make integration-test
    before_cache:
    - sudo chown -R travis:travis ./.go
    after_script:
    - make stop-kind
env:
  global:
  - secure: zw7R+A4MZQDt6yFG8xLFJsV8L0iV//RXz8e1jn13qjnKWvfHpXyT+gnJnj/sKH2caaeOaije7ti8iyn1/hh8nilWPifaD2dZL8Vc3cyK4jBt9rMNy/LQIlvZHy1hn16HyCcoYPxi/u/DnnjfEA3z2KZmmfPcSkIaKr/dE6xKFj9kj9fHUcuMBBnD4FEXVWDlfde2cDzmtMNYtElhTLLoFZ4RRFi9kNicvOUPIUzKxhxDxPbeycQkGgNUZFgk0Kc6UP3IRr9LjFSEWmWzOO2AbpxDlqTGNLhQLMn9YJcQQGN9L4byWB/JTvCL6owcXoVVdVO66d+tHlYL6m4Gv7W+nZERbFFH803W3/fsqIGLRaaW+aSRJn9/FF62dAuIekJckxjn3bj63e1EUd2OnQF9iiOdRYzq1pBxO2ii4f5Dp7veMS/kDFB+TK2mEb5yo8uQFtSxoeV3he9k+c5Z/9BdHdicXlG7kiJ1UFpb4mTOlxdu3sA+F2KROR/HbpCrlHTWxHEwQKmDsTT1kYzul5B4TMeUCoOqUxNeL5i7Z6JQBfGttMDrNwgk+nAjNgYuPkjCJUmI7TwmsmS+32Ahl+daN+gylumwyU1rkIf6Lq9Xpr/rA0xVgICLA54bRIPA8BD46OOixAtgAX/1y4KuXSB00hzsr+W6jejBHdWvvI0CJVg=
  - secure: tBMBkpNKV/WI6MDtLMPBD4/WvRh9WPZJw63vMhAa4R2AmcG/WgNsucWglc7DwZwVfIQ3g+2eZ+YV87raSMhbxiCkfqU67ww6ODmg8M45H5DBF3TlqmUU6cS4XIUQ2PmpNCJATuq0XZxz8NrKdkx3TTZrsOjEC8vikfIGEQuy+lbJ9Zf/svJi/cvuaAzCrAImLtg7fLYHaBB+pngWzp08iAXxE0CWLIXUzA7fnkpECHGMz8HNPkwLmGtVJKR2UFhx94QvuDSaUVKiiTWZLBc0nYJZvZ/xtnzSVCQHqQuuuBn1NfaOFxhMbZD+CFk0ssGT0PkjY2yuv8D51rTdvq16EyiTRRW6d5BYJpbijHpi/QHwKYkmNIdD8oAYAgl6TBcKLSlvvAmQYKKZYN024uDXzfiis9V9ABXuHdIr0dok/UahFFRyHgLVOExaGojPfMo2Ajm/Ni4dGlStav5u1JHWoGjLbozeD4OZ8hO0JdWl/qlXZTelYND9yzvmrcYPXtz98ALjBsDEVlnxoa/AfynD3aQ+OzwWd05r/8mURoHFnvbCGEvFteNkRSnfp97C24CQ7u02STu+VyuZ2ydpm5n+EytT1OUxtqtDhZFz975zfRq7pfEB3kX+yN3AiG+B6yJaaMsflJtFVWjulOFiPr1wXbnH1PqO/2o1SPAhSrHSq3A=
  - secure: ys1d5ls5fy5syA0NSpty7cRCbbTNwAnRASIx+H1k741tK8UmZf8/pSNgYaUeu6vNXHWHoxQDhUet9puZph7EcIQ5MeF6ERKwDiPuFuiCXZXAmuFTeAg5AxiD6bhVfq288KQBk9Gl7NkLV7SmJvFuftI29eJ5Bqr4avAPCdQ/ZCRsXopa8IOboqsDr6ygfMjaSnGGt2qKrEf7t9QxBoF9xIlJiL0wQ9tIMKmMYnKR5FDYlkKVDE5O6HNEPZ3RjXjjvsu17KSaqfaTo8vkbGKCYJj0ViSOTVM5vUEjA/rDwAp6BoUs6vwHxt7IYxdaYUb6RHVoxhNc0GHpCXoVzreO1l+XkGlJ/XD9JX4jJ6B/G9v2VslC/l1ApjcG/kPjSTyWAcfJyUoC5hp75c4Ua1LRqftuN7FJ11spc+Wb1b4ndxKR/Odt2+F8Yuh1s3rYlkGdMmAmahyuUjj3qqPvEtauGEOi6IQBOzhpFM5BHyIUU8D78dlGkOIBkViBRpo29s2ominWqnF7yRnocdpHqmQWTPV2sM+4dQi7Nx8EiBU+p/csOykg7Jvrf8y1xd/RdY5vvgPzEv/vdu45oOLFR62JWU44UGGtDaz4XEwjlQ+WxlDxILM7PNli7RpsdELgBw5BG80SgQbkn2DDIkJOPYjAMUBXGBBiXozg74/tFI736bo=
