apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kasten.io/config: dataservice
  name: dbconfig
data:
  docdb.instanceid: prasad-docdb-instance
  docdb.host: prasad-docdb-instance.test.us-west-2.rds.amazonaws.com
  docdb.user: docdb
  docdb.secret: dbcreds # name of K8s secret in the same namespace
